export const MuiButton = {
  styleOverrides: {
    root: ({ ownerState }) => ({
      boxSizing: 'border-box',
      borderRadius: '6px',
      margin: '0',
      ...(ownerState.margin && {
        margin: ownerState.margin,
      }),
      textTransform: 'none',
      width: 'fit-content',
      ...(ownerState.width && {
        width: ownerState.width,
      }),
      ...(ownerState.fullWidth && {
        width: '100%',
      }),
      ...(ownerState.maxWidth && {
        maxWidth: ownerState.maxWidth,
      }),
      ...(ownerState.minWidth && {
        minWidth: ownerState.minWidth,
      }),
      fontSize: '1rem',
      boxShadow: '0 1px 3px 0 rgb(33 36 41 / 20%)',
      '&:hover': {
        boxShadow: '0 1px 3px 0 rgb(33 36 41 / 20%)',
      },
    }),
    text: {
      boxShadow: 'none',
      '&:hover': {
        boxShadow: 'none',
      },
    },
    textInherit: {},
    textPrimary: {},
    textSecondary: {},
    textSuccess: {},
    textError: {},
    textInfo: {},
    textWarning: {},
    outlined: ({ ownerState, theme }) => ({
      borderWidth: '2px',
      ...(ownerState.color && {
        borderColor: theme.palette[ownerState.color].main,
      }),

      '&:hover': {
        ...(ownerState.color && {
          backgroundColor: theme.palette[ownerState.color].main,
          color: theme.palette[ownerState.color].contrastText,
          borderWidth: '2px',
        }),
      },
    }),
    outlinedInherit: {},
    outlinedPrimary: {},
    outlinedSecondary: {},
    outlinedSuccess: {},
    outlinedError: {},
    outlinedInfo: {},
    outlinedWarning: {},
    contained: {},
    containedInherit: {},
    containedPrimary: {},
    containedSecondary: {},
    containedSuccess: {},
    containedInfo: {},
    containedError: {},
    containedWarning: {},
    disableElevation: {},
    focusVisible: {},
    disabled: {},
    colorInherit: {},
    textSizeSmall: {},
    textSizeMedium: {},
    textSizeLarge: {},
    outlinedSizeSmall: { padding: '0.5225rem 0.96rem' },
    outlinedSizeMedium: { padding: '0.5625rem 1rem' },
    outlinedSizeLarge: { padding: '0.875rem 1.75rem' },
    containedSizeSmall: {},
    containedSizeMedium: {},
    containedSizeLarge: {},
    sizeSmall: {
      fontSize: '0.925rem',
      lineHeight: '0.925rem',
      fontWeight: 400,
      letterSpacing: '0.0225rem',
      padding: '0.6475rem 1.085rem',
    },
    sizeMedium: {
      fontSize: '0.9375rem',
      lineHeight: '0.9375rem',
      fontWeight: 600,
      letterSpacing: '0.03rem',
      padding: '0.6875rem 1.125rem',
    },
    sizeLarge: {
      fontSize: '1.25rem',
      lineHeight: '1.375rem',
      fontWeight: 600,
      letterSpacing: '0.0375rem',
      padding: '1rem 1.875rem',
    },
    fullWidth: {},
    startIcon: {},
    endIcon: {},
    iconSizeSmall: {},
    iconSizeMedium: {},
    iconSizeLarge: {},
  },
  defaultProps: {
    variant: 'contained',
  },
};
